/* ============================================================
   AUTOMATIC ENGINEERING PROJECT SYSTEM
   ------------------------------------------------------------
   Automatically loads project-index.json generated by
   GitHub Actions.

   Supports:
   FDAS
   CCTV
   ELV
   Microwave
   PCB
   Electronics
   and future categories.
   ============================================================ */

(function () {

    "use strict";


    /* ========================================================
       CONFIGURATION
       ======================================================== */

    const PROJECT_INDEX_FILE = "project-index.json";


    /* ========================================================
       HELPER: ESCAPE HTML
       ======================================================== */

    function escapeHTML(value) {

        return String(value)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }


    /* ========================================================
       HELPER: CREATE FILE URL
       ======================================================== */

    function createFileURL(relativePath) {

        const parts = relativePath
            .split("/")
            .map(function (part) {
                return encodeURIComponent(part);
            });

        return parts.join("/");
    }


    /* ========================================================
       CREATE FILE CARD
       ======================================================== */

    function createFileItem(filePath) {

        const fileName = filePath.split("/").pop();

        const link = document.createElement("a");

        link.className = "automatic-file-item";

        link.href = createFileURL(filePath);

        link.target = "_blank";

        link.rel = "noopener noreferrer";

        link.innerHTML = `
            <span class="automatic-file-icon">PDF</span>
            <span class="automatic-file-name">
                ${escapeHTML(fileName)}
            </span>
            <span class="automatic-file-arrow">↗</span>
        `;

        return link;
    }


    /* ========================================================
       CREATE PROJECT CARD
       ======================================================== */

    function createClientProjectCard(project, number) {

        const card = document.createElement("article");

        card.className = "automatic-client-project-card";


        const files = Array.isArray(project.files)
            ? project.files
            : [];


        let filesHTML = "";


        if (files.length > 0) {

            const filesContainer = document.createElement("div");

            filesContainer.className = "automatic-project-files";


            files.forEach(function (filePath) {

                filesContainer.appendChild(
                    createFileItem(filePath)
                );

            });


            card.innerHTML = `
                <div class="automatic-project-number">
                    ${String(number).padStart(2, "0")}
                </div>

                <div class="automatic-project-type">
                    ${escapeHTML(project.type)}
                </div>

                <h3>
                    ${escapeHTML(project.name)}
                </h3>

                <p class="automatic-project-description">
                    ${escapeHTML(project.type)}
                    project documentation and engineering
                    design files.
                </p>

                <div class="automatic-project-tags">
                    <span>${escapeHTML(project.category)}</span>
                    <span>${escapeHTML(project.type)}</span>
                    <span>${files.length} PDF${files.length === 1 ? "" : "s"}</span>
                </div>

                <div class="automatic-files-title">
                    PROJECT DOCUMENTATION
                </div>
            `;

            card.appendChild(filesContainer);

        } else {

            card.innerHTML = `
                <div class="automatic-project-number">
                    ${String(number).padStart(2, "0")}
                </div>

                <div class="automatic-project-type">
                    ${escapeHTML(project.type)}
                </div>

                <h3>
                    ${escapeHTML(project.name)}
                </h3>

                <p class="automatic-project-description">
                    ${escapeHTML(project.type)}
                    project documentation and engineering
                    design files.
                </p>

                <div class="automatic-project-tags">
                    <span>${escapeHTML(project.category)}</span>
                    <span>${escapeHTML(project.type)}</span>
                </div>

                <div class="automatic-no-files">
                    No PDF documentation has been added yet.
                </div>
            `;

        }


        return card;
    }


    /* ========================================================
       LOAD CLIENT PROJECTS
       ======================================================== */

    async function loadClientProjects(container) {

        const category =
            container.dataset.projectCategory;


        if (!category) {

            container.innerHTML = `
                <div class="automatic-error">
                    Project category is not defined.
                </div>
            `;

            return;
        }


        container.innerHTML = `
            <div class="automatic-loading">
                Loading projects...
            </div>
        `;


        try {

            const response = await fetch(
                PROJECT_INDEX_FILE + "?v=" + Date.now(),
                {
                    cache: "no-store"
                }
            );


            if (!response.ok) {

                throw new Error(
                    "Unable to load project-index.json."
                );

            }


            const data = await response.json();


            if (!data.categories) {

                throw new Error(
                    "Project index does not contain categories."
                );

            }


            const categoryData =
                data.categories[category];


            container.innerHTML = "";


            if (!categoryData) {

                container.innerHTML = `
                    <div class="automatic-empty">
                        No projects have been added to
                        ${escapeHTML(category)} yet.
                    </div>
                `;

                return;
            }


            const projects =
                Array.isArray(categoryData.clientProjects)
                    ? categoryData.clientProjects
                    : [];


            if (projects.length === 0) {

                container.innerHTML = `
                    <div class="automatic-empty">
                        No client projects have been added
                        to ${escapeHTML(category)} yet.
                    </div>
                `;

                return;
            }


            const grid =
                document.createElement("div");

            grid.className =
                "automatic-client-project-grid";


            projects.forEach(function (project, index) {

                grid.appendChild(
                    createClientProjectCard(
                        project,
                        index + 1
                    )
                );

            });


            container.appendChild(grid);


        } catch (error) {

            console.error(
                "Automatic project system error:",
                error
            );


            container.innerHTML = `
                <div class="automatic-error">

                    <strong>
                        Unable to load client projects.
                    </strong>

                    <p>
                        ${escapeHTML(error.message)}
                    </p>

                </div>
            `;

        }

    }


    /* ========================================================
       LOAD ALL AUTOMATIC CLIENT PROJECT CONTAINERS
       ======================================================== */

    function initializeAutomaticProjects() {

        const containers =
            document.querySelectorAll(
                "[data-project-category]"
            );


        containers.forEach(function (container) {

            loadClientProjects(container);

        });

    }


    /* ========================================================
       LOAD EXISTING SELF-DIRECTED FILE SYSTEM
       --------------------------------------------------------
       This keeps compatibility with the existing
       data-project-files="Files/FDAS" system.
       ======================================================== */

    async function loadProjectFiles(container) {

        const folder =
            container.dataset.projectFiles;


        if (!folder) {
            return;
        }


        container.innerHTML = `
            <div class="automatic-loading">
                Loading project files...
            </div>
        `;


        try {

            const response = await fetch(
                folder + "/files.json?v=" + Date.now(),
                {
                    cache: "no-store"
                }
            );


            if (!response.ok) {

                throw new Error(
                    "Unable to load project files."
                );

            }


            const data =
                await response.json();


            let files = [];


            if (Array.isArray(data)) {

                files = data;

            } else if (Array.isArray(data.files)) {

                files = data.files;

            }


            container.innerHTML = "";


            if (files.length === 0) {

                container.innerHTML = `
                    <div class="automatic-empty">
                        No project documentation has been
                        added yet.
                    </div>
                `;

                return;
            }


            const filesContainer =
                document.createElement("div");

            filesContainer.className =
                "automatic-project-files";


            files.forEach(function (file) {

                let path;


                if (typeof file === "string") {

                    path =
                        folder + "/" + file;

                } else if (
                    file &&
                    typeof file.path === "string"
                ) {

                    path =
                        folder + "/" + file.path;

                } else {

                    return;

                }


                filesContainer.appendChild(
                    createFileItem(path)
                );

            });


            container.appendChild(filesContainer);


        } catch (error) {

            console.error(
                "Project file loading error:",
                error
            );


            container.innerHTML = `
                <div class="automatic-error">

                    <strong>
                        Unable to load project files.
                    </strong>

                    <p>
                        ${escapeHTML(error.message)}
                    </p>

                </div>
            `;

        }

    }


    /* ========================================================
       INITIALIZE EXISTING FILE CONTAINERS
       ======================================================== */

    function initializeProjectFiles() {

        const containers =
            document.querySelectorAll(
                "[data-project-files]"
            );


        containers.forEach(function (container) {

            loadProjectFiles(container);

        });

    }


    /* ========================================================
       INITIALIZE
       ======================================================== */

    function initialize() {

        initializeAutomaticProjects();

        initializeProjectFiles();

    }


    if (document.readyState === "loading") {

        document.addEventListener(
            "DOMContentLoaded",
            initialize
        );

    } else {

        initialize();

    }

})();
